### ISSUE TITLE
Localhost 8080 and 8081 not working

### ISSUE THREAD

**Issue by nanningdejong** [Haarlem/digitale-waardepapieren#27]
Localhost:8082 seems to work, but not 8080 and 8081. Both claim_page_1 and scanner_1 seem to be bound to port 8080? 

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
917a3b8c19e9        node:9.2.0          "bash -c 'npm instal…"   5 minutes ago       Up 5 minutes        0.0.0.0:8080->8080/tcp   digitalewaardepapierendevelop_claim_page_1
ddfb8ccc5e6c        node:9.2.0          "bash -c 'npm instal…"   5 minutes ago       Up 5 minutes        0.0.0.0:8081->8080/tcp   digitalewaardepapierendevelop_scanner_1
120cf556fd77        node:9.2.0          "bash -c 'npm instal…"   5 minutes ago       Up 5 minutes        0.0.0.0:8082->8082/tcp   digitalewaardepapierendevelop_claim_server_1

Thanks!

**Comment by nanningdejong** [comment]
I changed the scanner port in docker-compose.dev.yml  and claim_page_1 now works

`scanner:
    image: node:9.2.0
    user: "node"
    working_dir: /home/node/app/Scanner
    command: 'bash -c "npm install && npm run dev"'
    volumes:
      - ./:/home/node/app
    ports:
      - 8081:8081`

**Comment by BoerBas** [comment]
Fixed it, thanks!
